import Foundation

extension ScreenplayStudioScreen {
    struct StudioDebugDiffState: Codable, Equatable {
        let debugSessionID: String
        let projectKey: String
        let selectedProjectID: String
        let latestVersionID: String
        let studioSurfaceActive: Bool
        let selectedProjectPresent: Bool
        let errorText: String
        let isSaving: Bool
        let loadedDraftProjectID: String
        let loadProjectToken: Int
        let loadProjectAckToken: Int
        let loadProjectRequestedProjectID: String
        let loadProjectRequestedVersionID: String
        let loadProjectStage: String
        let loadProjectReady: Bool
        let loadProjectError: String
        let editorFocusPending: Bool
        let preparedPromptToken: Int
        let preparedPromptText: String
        let preparedPromptRouting: String
        let composerFocused: Bool
        let composerExpanded: Bool
        let submitInFlight: Bool
        let submitCommandReceivedToken: Int
        let submitAckToken: Int
        let submitAckText: String
        let submitAckRouting: String
        let submitAckReplacementMode: String
        let submitAckRequestID: String
        let commandBarToken: Int
        let commandBarAckToken: Int
        let hasPendingReplacementTarget: Bool
        let pendingReplacementWriteID: String
        let pendingReplacementStartLine: Int?
        let pendingReplacementEndLine: Int?
        let pendingReplacementPreview: String
        let hasSubmittedReplacementTarget: Bool
        let submittedReplacementWriteID: String
        let submittedReplacementStartLine: Int?
        let submittedReplacementEndLine: Int?
        let submittedReplacementPreview: String
        let revisedDiffCount: Int
        let reopenedDiffCount: Int
        let acknowledgedDiffCount: Int
        let askNoteHistoryCount: Int
        let backendAskNoteHistoryCount: Int
        let latestAskNotePrompt: String
        let latestAskNoteInsertedText: String
        let latestRevisedKey: String
        let latestRevisedLineageKey: String
        let latestRevisedWriteID: String
        let focusedDiffLineageKey: String
        let focusedDiffWriteID: String
        let activeRevisedKey: String
        let activeRevisedLineageKey: String
        let activeRevisedWriteID: String
        let activeLineageRevisedKeys: [String]
        let activeLineageRevisedWriteIDs: [String]
        let latestReopenedKey: String
        let latestReopenedLineageKey: String
        let latestReopenedWriteID: String
        let restoredStateSource: String
        let restoredFocusedDiffSource: String
        let restoredReopenedSource: String
        let restoredFocusedDiffKey: String
        let restoredReopenedLineageKeys: [String]
        let restoredLatestReopenedWriteID: String
        let localThreadStateKeyPresent: Bool
        let localThreadStateFocusedDiffKey: String
        let localThreadStateReopenedLineageKeys: [String]
        let localThreadStateLatestReopenedWriteID: String
        let latestAcknowledgedLineageKey: String
        let latestAcknowledgedWriteID: String
        let latestAcknowledgedFingerprint: String
        let backendSelectedProjectID: String
        let backendSelectedFocusedDiffKey: String
        let backendSelectedReopenedLineageKeys: [String]
        let backendSelectedLatestReopenedWriteID: String
        let backendSelectedAcknowledgedKeysCount: Int
        let backendSelectedAcknowledgedEntriesCount: Int
        let backendListedFocusedDiffKey: String
        let backendListedReopenedLineageKeys: [String]
        let backendListedLatestReopenedWriteID: String
        let backendListedAcknowledgedKeysCount: Int
        let backendListedAcknowledgedEntriesCount: Int
        let isManualDraftEditing: Bool
        let hasUnsavedDraftChanges: Bool
        let autosaveEnabled: Bool
        let autosaveStatusText: String
        let conflictPresent: Bool
        let conflictProjectID: String
        let conflictBaseVersionID: String
        let conflictServerVersionID: String
        let conflictServerDraftPreview: String
        let recoveryPresent: Bool
        let recoveryProjectID: String
        let recoveryBaseVersionID: String
        let recoverySavedAt: TimeInterval
        let recoveryDraftPreview: String
        let recoveryMatchesCurrentDraft: Bool
        let leftSidebarVisible: Bool
        let sidebarSection: String
        let draftInspectorPresented: Bool
        let draftInspectorSection: String
        let draftPaginationPageCount: Int
        let draftIntegrityIssueCount: Int
        let draftIntegrityCanMoveToPin: Bool
        let draftIntegrityCanMoveAllToPin: Bool
        let draftIntegrityPrimaryPreview: String
        let infoText: String
        let draftPreview: String
        let draftTailPreview: String
        let draftCharacterCount: Int
        let draftFingerprint: String
        let focusedDiffKey: String
        let latestThreadRequestID: String
        let latestThreadWriteID: String
        let latestThreadReplacedWriteID: String
        let latestThreadReplacementApplied: Bool
        let latestThreadPrompt: String
        let latestThreadInsertedPreview: String
        let latestThreadMemoryLabel: String
        let latestThreadMemoryValue: String
        let latestThreadOutputLabel: String
        let latestThreadOutputValue: String
        let footerMemoryLabel: String
        let footerMemoryValue: String
        let footerOutputLabel: String
        let footerOutputValue: String
        let transientStatusVisible: Bool
        let pageWriteToastVisible: Bool
        let pageWriteToastCollapsed: Bool
        let pageWriteToastSource: String
        let pageWriteToastPreview: String
        let voicePinTurnCount: Int
        let voicePinEmpty: Bool
        let collaboratorCount: Int
        let approvedEmails: [String]
        let commentCount: Int
        let latestCommentID: String
        let latestCommentText: String
        let latestCommentAuthor: String
        let latestCommentResolved: Bool
        let latestCommentDeleted: Bool
        let collaboratorInspectorCompact: Bool
        let themCompanionMode: String
        let themUnifiedSurface: Bool
        let themModeControlStyle: String
        let themRecentThreadInlineSummaryVisible: Bool
        let intelligenceQueueCount: Int
        let intelligenceQueueSafeCount: Int
        let intelligenceQueueTitles: [String]
        let intelligenceLastBatchID: String
        let intelligenceLastBatchAppliedCount: Int
        let featureCompassAct: String
        let featureCompassNextScene: String
        let featureCompassMoveTitles: [String]
        let featureCompassAcceptedBatchCount: Int
        let featureCompassAcceptedBatchDetail: String
        let featureCompassHasAcceptedBatch: Bool
        let rightRailExpanded: Bool
        let rightPanelTab: String
        let selectedBeatID: String
        let selectedBeatLabel: String
        let selectedBeatSummary: String
        let selectedBeatSceneID: String
        let selectedBeatActID: String
        let selectedBeatProvenance: String
        let beatDraftLabel: String
        let beatDraftSummary: String
        let beatOrderIDs: [String]
        let beatOrderLabels: [String]
        let beatDragInFlight: Bool
        let draggedBeatID: String
        let beatDropTargetID: String
        let beatInsertionMarkerVisible: Bool
        let beatEndDropVisible: Bool
        let beatEndDropTargeted: Bool
        let inspectorAutoScrollAnchorID: String
        let inspectorAutoScrollDirection: String
        let highlightedSceneInspectorKey: String
        let selectionStartLine: Int
        let selectionEndLine: Int
    }

    struct StudioDebugProjectLoadBreadcrumb: Codable, Equatable {
        let token: Int
        let event: String
        let detail: String
        let requestedProjectID: String
        let requestedVersionID: String
        let selectedProjectID: String
        let latestVersionID: String
        let loadedDraftProjectID: String
        let isLoading: Bool
        let hasSelectedProject: Bool
        let editorFocusPending: Bool
        let timestampISO8601: String
    }

    struct StudioDebugSubmitResultPayload: Codable, Equatable {
        let token: Int
        let status: String
        let transport: String
        let requestID: String
        let prompt: String
        let routingMode: String
        let target: String
        let memoryDomain: String
        let companionMode: String
        let noteTitle: String
        let noteBody: String
        let developmentText: String
        let insertedText: String
        let error: String
    }
}
