// Craft Cards — 20-card library selectable by tone+genre
// No backend/index.js growth. D009 strangler.

export const CRAFT_CARDS = [
  {
    id: "cc-01",
    title: "Want Hides Need",
    category: "want",
    want: "Protagonist wants external prize that masks inner need",
    obstacle: "Prize requires betraying need; mentor tests it",
    cost: "Keep prize → lose self; choose need → lose prize",
    imageEcho: "Opening want-object returns broken in final image",
    subtext: "Dialogue about prize, scene about fear of worthlessness",
    motif: "kept object / photo that changes meaning",
    technique: "Plant want early, reveal need at midpoint reversal",
    example: "Thriller: wants promotion vs needs to quit lying",
    genres: ["drama", "thriller", "romance"],
    tones: ["tense", "melancholic", "dark"],
  },
  {
    id: "cc-02",
    title: "Obstacle Is a Person",
    category: "obstacle",
    want: "Clear external want",
    obstacle: "Antagonist who wants same prize for opposite reason",
    cost: "Beat them by becoming them; cost is mirrored flaw",
    imageEcho: "Same room, same blocking — roles reversed",
    subtext: "Polite surface, status shift underneath each line",
    motif: "mirror / double casting",
    technique: "Give antagonist a valid want; let hero borrow their tactic",
    example: "Horror: final girl must use killer's ritual",
    genres: ["thriller", "horror", "action"],
    tones: ["dark", "tense", "cynical"],
  },
  {
    id: "cc-03",
    title: "Cost Up Front",
    category: "cost",
    want: "Small want that promises big win",
    obstacle: "Win demands visible sacrifice in act one",
    cost: "Pay cost early; audience bets you can't bear act-three price",
    imageEcho: "Burned bridge in act one, smoke still in final frame",
    subtext: "Joke about sacrifice before sacrifice matters",
    motif: "scar / burnt letter",
    technique: "Make cost physical and irreversible by p25",
    example: "Sci-fi: trade memory for passage",
    genres: ["sci-fi", "fantasy", "drama"],
    tones: ["melancholic", "dark", "uplifting"],
  },
  {
    id: "cc-04",
    title: "Image Echo",
    category: "image",
    want: "Introduce visual promise",
    obstacle: "World normalizes forgetting the image",
    cost: "Recall costs comfort; restored image hurts",
    imageEcho: "Orbital window / fake set glitch returns with stain",
    subtext: "Character says image doesn't matter — holds it longest",
    motif: "window / glitch / echo",
    technique: "Bookend same composition, light changes, meaning flips",
    example: "Sci-fi: fake set becomes proof",
    genres: ["sci-fi", "horror", "mystery"],
    tones: ["dark", "melancholic", "tense"],
  },
  {
    id: "cc-05",
    title: "Subtext Is Status",
    category: "subtext",
    want: "Wants approval in scene",
    obstacle: "Other character holds approval hostage",
    cost: "Win approval by admitting need — loses power",
    imageEcho: "Seating / height shifts without dialogue cue",
    subtext: "Every line says yes while no builds underneath",
    motif: "unspoken truth / withheld line",
    technique: "Write dialogue on topic, scene about power",
    example: "Comedy: pitch meeting where joke is armor",
    genres: ["comedy", "drama", "romance"],
    tones: ["whimsical", "cynical", "tense"],
  },
  {
    id: "cc-06",
    title: "Motif Becomes Plot",
    category: "motif",
    want: "Introduce harmless motif",
    obstacle: "Motif ignored until it blocks protagonist",
    cost: "Use motif to win; motif now carries guilt",
    imageEcho: "Running gag prop returns as evidence",
    subtext: "Play motif for laughs, payoff for silence",
    motif: "running gag becomes truth",
    technique: "Repeat motif 3 times, 3rd changes function",
    example: "Comedy: lie-prop becomes confession",
    genres: ["comedy", "mystery", "drama"],
    tones: ["whimsical", "cynical", "uplifting"],
  },
  {
    id: "cc-07",
    title: "Clock & Consequence",
    category: "cost",
    want: "Beat the clock",
    obstacle: "Clock is person: deadline enforcer with leverage",
    cost: "Make deadline by sacrificing relationship",
    imageEcho: "Ticking clock in bg, stopped clock in final shot",
    subtext: "Talk about time, act about abandonment",
    motif: "ticking clock / missed call",
    technique: "Audible clock + visible cost trade every 10 pages",
    example: "Thriller: 48h to prove innocence",
    genres: ["thriller", "action", "horror"],
    tones: ["tense", "dark", "cynical"],
  },
  {
    id: "cc-08",
    title: "Want vs Love",
    category: "want",
    want: "Want that costs love",
    obstacle: "Love interest embodies obstacle to want",
    cost: "Choose want → lose love; choose love → lose want",
    imageEcho: "Kept object / letter never sent, sent at end",
    subtext: "Love scenes argue logistics, not feelings",
    motif: "letter / kept object",
    technique: "Make love cost same currency as want",
    example: "Romance: career vs staying",
    genres: ["romance", "drama", "comedy"],
    tones: ["melancholic", "uplifting", "whimsical"],
  },
  {
    id: "cc-09",
    title: "Obstacle Is System",
    category: "obstacle",
    want: "Individual win",
    obstacle: "System that rewards flaw; winning plays its game",
    cost: "Beat system by refusing prize it offers",
    imageEcho: "Hallway of doors — same hallway, one door missing",
    subtext: "Bureaucratic politeness masks threat",
    motif: "hallway / fluorescent grid",
    technique: "Personify system in one clerk who loves rules",
    example: "Drama: whistleblower",
    genres: ["drama", "sci-fi", "thriller"],
    tones: ["cynical", "tense", "dark"],
  },
  {
    id: "cc-10",
    title: "Quiet Cost",
    category: "cost",
    want: "Small, decent want",
    obstacle: "Decent path is slow; shortcut costs soul",
    cost: "Take shortcut; win is hollow and visible",
    imageEcho: "Clean hands → stained hands same sink",
    subtext: "All lines are practical, guilt is in pauses",
    motif: "stain / window light / dust",
    technique: "Show cost in action line, not dialogue",
    example: "Drama: small lie to protect family",
    genres: ["drama", "mystery", "romance"],
    tones: ["melancholic", "dark", "grounded"],
  },
  {
    id: "cc-11",
    title: "Dread Geography",
    category: "image",
    want: "Safety of home",
    obstacle: "Home is listening / remembers",
    cost: "Leave home to save it; return as stranger",
    imageEcho: "Room tone / shadow that wasn't there on page one",
    subtext: "Characters talk chores while listening for house",
    motif: "listening shadow / memory of room",
    technique: "Repeat location with one added detail each return",
    example: "Horror: house keeps everyone",
    genres: ["horror", "mystery", "drama"],
    tones: ["dark", "tense", "melancholic"],
  },
  {
    id: "cc-12",
    title: "Lie Becomes Truth",
    category: "subtext",
    want: "Sell the lie",
    obstacle: "Lie works too well; people love liar",
    cost: "Keep lie → keep love built on lie; confess → lose both",
    imageEcho: "Costume/mask kept after reveal",
    subtext: "Joke is armor; earnest line lands after two jokes",
    motif: "mask / costume",
    technique: "Escalate lie in set pieces, tag is truth",
    example: "Comedy: fake expertise",
    genres: ["comedy", "romance", "fantasy"],
    tones: ["whimsical", "uplifting", "cynical"],
  },
  {
    id: "cc-13",
    title: "Relic With Price",
    category: "motif",
    want: "Claim the relic / power",
    obstacle: "Guardian who already paid price warns",
    cost: "Use relic; pay same price guardian paid",
    imageEcho: "Map/relic glows → dulls after use",
    subtext: "Awe lines, actor plays fear",
    motif: "relic / map",
    technique: "One rule for relic, break it once at cost",
    example: "Fantasy: trials to earn blade",
    genres: ["fantasy", "action", "sci-fi"],
    tones: ["uplifting", "dark", "tense"],
  },
  {
    id: "cc-14",
    title: "Missing Piece",
    category: "obstacle",
    want: "Solve case / restore order",
    obstacle: "One clue missing because detective's flaw hides it",
    cost: "See truth → admit flaw cost public image",
    imageEcho: "Evidence board — one string moves, whole board flips",
    subtext: "Questions are accusations in polite form",
    motif: "missing piece / string board",
    technique: "Withhold one piece the detective already has but won't see",
    example: "Mystery: blind spot is loyalty",
    genres: ["mystery", "thriller", "drama"],
    tones: ["tense", "cynical", "dark"],
  },
  {
    id: "cc-15",
    title: "Weapon As Character",
    category: "image",
    want: "Win the fight",
    obstacle: "Weapon/vehicle demands reckless partner",
    cost: "Win fight, lose machine that saved you",
    imageEcho: "Vehicle/weapon introduced pristine, ends scarred",
    subtext: "Talk specs, scene about trust",
    motif: "weapon / vehicle as character",
    technique: "Give tool a want and a limit; break limit at midpoint",
    example: "Action: last drive",
    genres: ["action", "sci-fi", "thriller"],
    tones: ["tense", "uplifting", "dark"],
  },
  {
    id: "cc-16",
    title: "Wonder Becomes Threat",
    category: "want",
    want: "Chase wonder / anomaly",
    obstacle: "Wonder's rule is threat when understood",
    cost: "Keep wonder → lose humanity; kill wonder → lose future",
    imageEcho: "Anomaly light warm → cold after midpoint",
    subtext: "Science talk, actor plays grief for world ending",
    motif: "fake set glitch / orbital window",
    technique: "Midpoint: wonder answers, answer is cost",
    example: "Sci-fi: new physics",
    genres: ["sci-fi", "fantasy", "horror"],
    tones: ["melancholic", "dark", "uplifting"],
  },
  {
    id: "cc-17",
    title: "Ensemble Want Clash",
    category: "obstacle",
    want: "Each character wants different ending",
    obstacle: "Only one ending can film; wants collide at midpoint",
    cost: "Choose one want; others pay",
    imageEcho: "Group photo composed same, one person steps out",
    subtext: "Team banter, camera tracks who isn't laughing",
    motif: "group photo / table seating",
    technique: "Assign each character a distinct comic/genre role; clash them",
    example: "Comedy/drama ensemble",
    genres: ["comedy", "drama", "action"],
    tones: ["whimsical", "cynical", "uplifting"],
  },
  {
    id: "cc-18",
    title: "Bittersweet Grace",
    category: "cost",
    want: "Reconciliation",
    obstacle: "Truth needed for grace costs image",
    cost: "Grace given without guarantee returned",
    imageEcho: "Unspoken truth finally said in same kitchen light",
    subtext: "Quiet lines, long holds on reaction not action",
    motif: "unspoken truth / kitchen light",
    technique: "Earn grace by choosing need over want in button",
    example: "Drama: apology without answer",
    genres: ["drama", "romance", "mystery"],
    tones: ["melancholic", "uplifting", "grounded"],
  },
  {
    id: "cc-19",
    title: "Truth Wins, Trust Lost",
    category: "cost",
    want: "Expose truth",
    obstacle: "Truth-teller is compromised",
    cost: "Win truth, lose trust of ally who lied for you",
    imageEcho: "Signal / recording played — room empties",
    subtext: "Dry reporting, loss is in who leaves",
    motif: "unreliable signal / recording",
    technique: "Midpoint twist is ally's betrayal was protection",
    example: "Thriller: source burns",
    genres: ["thriller", "mystery", "drama"],
    tones: ["cynical", "tense", "dark"],
  },
  {
    id: "cc-20",
    title: "Tag Restores With Scar",
    category: "motif",
    want: "Return to status quo",
    obstacle: "Status quo remembers cost",
    cost: "Restored world has scar; show it in final image",
    imageEcho: "Final girl cost — same porch, limp kept",
    subtext: "Tag joke lands because cost is still visible",
    motif: "scar / porch / tag",
    technique: "Return to opening location, one detail permanently changed",
    example: "Horror/comedy tag",
    genres: ["horror", "comedy", "action"],
    tones: ["dark", "whimsical", "uplifting"],
  },
];

const TONE_SYNONYMS = Object.freeze({ dark: ["dark", "tense"], tense: ["tense", "dark"] });

export function selectCraftCards({ genre, tone } = {}) {
  const g = genre ? String(genre).trim().toLowerCase() : null;
  const t = tone ? String(tone).trim().toLowerCase() : null;
  if (!g && !t) return [...CRAFT_CARDS];
  const tAliases = t && TONE_SYNONYMS[t] ? TONE_SYNONYMS[t] : (t ? [t] : []);
  const scored = CRAFT_CARDS.map((c) => {
    let score = 0;
    const gl = c.genres.map((x) => x.toLowerCase());
    const tl = c.tones.map((x) => x.toLowerCase());
    if (g && gl.includes(g)) score += 2;
    if (t && tAliases.some((a) => tl.includes(a))) score += 2;
    // bonus if card is universal-ish (covers 3+ genres) when no direct match fallback handled elsewhere
    return { c, score };
  });
  const matched = scored.filter((s) => s.score > 0).sort((a, b) => b.score - a.score).map((s) => s.c);
  if (matched.length > 0) return matched;
  // no direct match: return 5 broadly useful cards
  return CRAFT_CARDS.slice(0, 5);
}

export default { CRAFT_CARDS, selectCraftCards };
